# tools/make_vic20_asm_inc.py
from __future__ import annotations

from math import sqrt
from pathlib import Path
import config

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
BUILD = ROOT / "build"


def q_table() -> bytes:
    q = []
    for x in range(256):
        q.append(min(int(sqrt(65536 - x * x)), 255))
    return bytes(q)


def word(n: int) -> str:
    if not 0 <= n <= 0xFFFF:
        raise ValueError(f"word out of range: {n}")
    return f"${n:04X}"


def byte(n: int) -> str:
    if not 0 <= n <= 0xFF:
        raise ValueError(f"byte out of range: {n}")
    return f"${n:02X}"




def checked_seed(value, label: str) -> tuple[int, int]:
    if len(value) != 2:
        raise ValueError(f"{label} must be a pair: (low, high)")
    lo, hi = int(value[0]), int(value[1])
    if not 0 <= lo <= 0xFF or not 0 <= hi <= 0xFF:
        raise ValueError(f"{label} seed bytes must be in range 0..255")
    return lo, hi


def config_seed(name: str, default: tuple[int, int]) -> tuple[int, int]:
    return checked_seed(getattr(config, name, default), name)


def drive_seed(device: int, default: tuple[int, int]) -> tuple[int, int]:
    seeds = getattr(config, "DRIVE_SEEDS", {})
    if isinstance(seeds, dict):
        value = seeds.get(device, default)
    else:
        value = default
    return checked_seed(value, f"DRIVE_SEEDS[{device}]")


def compact_drive_image() -> bytes:
    raw_path = BUILD / "vic20_drive.bin"
    raw = raw_path.read_bytes()
    body = raw.rstrip(b"\x00")
    if not body:
        raise ValueError(f"{raw_path} is empty after trimming")
    out = BUILD / "vic20_asm_drive.bin"
    out.write_bytes(body)
    return body


def split_vic_drive(total: int, vic_weight: int, drive_weight: int, drives: int) -> tuple[int, list[int]]:
    if drives == 0:
        return total, []
    w = vic_weight + drives * drive_weight
    nv = total * vic_weight // w
    rem = total - nv
    per = rem // drives
    chunks = [per] * drives
    chunks[-1] += rem - per * drives
    return nv, chunks


def mode_tables(total: int, vic_weight: int, drive_weight: int):
    # Modes match the current VIC-20 + 3K BASIC variant:
    # 1: V only; 2: V+D8; 3: V+D8+D9; 4: V+D8+D9+D10; 5: D8+D9+D10.
    rows = []
    rows.append((total, 0, 0, 0))
    nv, ds = split_vic_drive(total, vic_weight, drive_weight, 1)
    rows.append((nv, ds[0], 0, 0))
    nv, ds = split_vic_drive(total, vic_weight, drive_weight, 2)
    rows.append((nv, ds[0], ds[1], 0))
    nv, ds = split_vic_drive(total, vic_weight, drive_weight, 3)
    rows.append((nv, ds[0], ds[1], ds[2]))
    per = total // 3
    rows.append((0, per, per, total - 2 * per))
    return rows


def main() -> None:
    total = int(config.TOTAL_WORK)
    jps = int(getattr(config, "JIFFIES_PER_SECOND", 50))
    if not 1 <= total <= 0xFFFF:
        raise ValueError("vic20_asm requires 1 <= TOTAL_WORK <= 65535")
    if not 1 <= jps <= 0xFFFF:
        raise ValueError("vic20_asm requires 1 <= JIFFIES_PER_SECOND <= 65535")

    d = config.DRIVE
    drive_image = compact_drive_image()
    q_offset = d["table"] - d["load"]
    if q_offset < 0 or q_offset + 256 > len(drive_image):
        raise ValueError("compact drive image does not contain the Q table")
    expected_q = q_table()
    if drive_image[q_offset:q_offset + 256] != expected_q:
        raise ValueError("compact drive image Q table does not match generated Q table")

    vic_weight = int(getattr(config, "VIC_WEIGHT", 100))
    drive_weight = int(config.DRIVE_WEIGHT)
    vic_seed = config_seed("VIC_SEED", (123, 45))
    d8_seed = drive_seed(8, (37, 21))
    d9_seed = drive_seed(9, (91, 173))
    d10_seed = drive_seed(10, (211, 57))
    rows = mode_tables(total, vic_weight, drive_weight)
    for row in rows:
        for value in row:
            if not 0 <= value <= 0xFFFF:
                raise ValueError(f"mode workload out of 16-bit range: {row}")
    workers = [sum(1 for v in row if v > 0) for row in rows]
    k_rows = [[v // 1000 if v else 0 for v in row] for row in rows]

    def words(col: int) -> str:
        return ",".join(word(row[col]) for row in rows)

    def bytes_col(values: list[int]) -> str:
        return ",".join(byte(v) for v in values)

    text = f"""; src/generated_vic20_asm.inc -- generated by tools/make_vic20_asm_inc.py

TOTAL_WORK      = {total}
JIFFIES_PER_SECOND = {jps}
DRIVE_LOAD      = {word(d['load'])}
DRIVE_PARAMS    = {word(d['params'])}
DRIVE_STATUS    = {word(d['params'] + 3)}
DRIVE_RESULT    = {word(d['params'] + 4)}
DRIVE_IMAGE_LEN = {len(drive_image)}
Q_OFFSET        = {word(q_offset)}

VIC_SEED_LO     = {byte(vic_seed[0])}
VIC_SEED_HI     = {byte(vic_seed[1])}
D8_SEED_LO      = {byte(d8_seed[0])}
D8_SEED_HI      = {byte(d8_seed[1])}
D9_SEED_LO      = {byte(d9_seed[0])}
D9_SEED_HI      = {byte(d9_seed[1])}
D10_SEED_LO     = {byte(d10_seed[0])}
D10_SEED_HI     = {byte(d10_seed[1])}

.segment \"RODATA\"
mode_nv:      .word {words(0)}
mode_n8:      .word {words(1)}
mode_n9:      .word {words(2)}
mode_na:      .word {words(3)}
mode_workers: .byte {bytes_col(workers)}
mode_kv:      .byte {bytes_col([row[0] for row in k_rows])}
mode_k8:      .byte {bytes_col([row[1] for row in k_rows])}
mode_k9:      .byte {bytes_col([row[2] for row in k_rows])}
mode_ka:      .byte {bytes_col([row[3] for row in k_rows])}
"""
    out = SRC / "generated_vic20_asm.inc"
    out.write_text(text, encoding="ascii", newline="\n")
    print(f"wrote {out}")
    print(f"wrote {BUILD / 'vic20_asm_drive.bin'}: {len(drive_image)} bytes")
    print(
        "VIC20 ASM config: "
        f"TOTAL_WORK={total}, "
        f"JIFFIES_PER_SECOND={jps}, "
        f"VIC_WEIGHT={vic_weight}, "
        f"DRIVE_WEIGHT={drive_weight}"
    )


if __name__ == "__main__":
    main()
