# tools/make_vic20uc_inc.py
from __future__ import annotations

from math import sqrt
from pathlib import Path
import config

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
BUILD = ROOT / "build"

OVERLAY_END = 0x2000
OVERLAY_LOAD = 0x1E20
OVERLAY_NAME = "vic20ucdrv"

# The contiguous 1541 PRG image is useful for diagnostics, but the C host does
# not embed the whole image in its below-screen memory.  The Q table remains in
# normal RODATA because the local VIC worker needs it after screen output starts.
# Upload-only drive payload is packed into a small overlay PRG loaded into VIC-20
# screen RAM after RUN and immediately copied to the 1541 drives.
SEGMENTS = [
    ("drive_seg_common", 0x0300, 0x0400, "DRIVEIMG"),
    ("q_table",          0x0400, 0x0500, "RODATA"),
    ("drive_seg_ctrl",   0x0500, 0x0580, "DRIVEIMG"),
    ("drive_seg_job_a",  0x0600, 0x0650, "DRIVEIMG"),
    ("drive_seg_job_b",  0x0700, 0x0750, "DRIVEIMG"),
]

PRESERVE_ZERO_SEGMENTS = {
    "drive_seg_job_a",
    "drive_seg_job_b",
}


def q_table() -> bytes:
    q: list[int] = []
    for x in range(256):
        q.append(min(int(sqrt(65536 - x * x)), 255))
    return bytes(q)


def checked_byte(value: int, name: str) -> int:
    value = int(value)
    if not 0 <= value <= 0xFF:
        raise ValueError(f"{name}: byte value out of range: {value}")
    return value


def checked_word(value: int, name: str) -> int:
    value = int(value)
    if not 0 <= value <= 0xFFFF:
        raise ValueError(f"{name}: word value out of range: {value}")
    return value


def seed_pair(name: str, value: tuple[int, int]) -> tuple[int, int]:
    lo, hi = value
    return checked_byte(lo, f"{name}[0]"), checked_byte(hi, f"{name}[1]")


def compact_drive_image() -> bytes:
    raw_path = BUILD / "vic20_drive.bin"
    raw = raw_path.read_bytes()
    body = raw.rstrip(b"\x00")
    if not body:
        raise ValueError(f"{raw_path} is empty after trimming")
    out = BUILD / "vic20uc_drive.bin"
    out.write_bytes(body)
    return body


def extract_segments(drive_image: bytes, drive_load: int) -> list[tuple[str, int, bytes, str]]:
    out: list[tuple[str, int, bytes, str]] = []
    for name, start, end, segment in SEGMENTS:
        off0 = start - drive_load
        off1 = end - drive_load
        if off0 < 0 or off0 >= len(drive_image):
            raise ValueError(f"segment {name}: start ${start:04X} outside compact drive image")
        seg_len = end - start
        chunk = drive_image[off0:min(off1, len(drive_image))]
        if len(chunk) < seg_len:
            chunk += bytes(seg_len - len(chunk))
        if name not in PRESERVE_ZERO_SEGMENTS:
            chunk = chunk.rstrip(b"\x00")
        if not chunk:
            raise ValueError(f"segment {name}: empty after trimming")
        out.append((name, start, chunk, segment))
    return out

def split_vic_drive(total: int, vic_weight: int, drive_weight: int, drives: int) -> tuple[int, list[int]]:
    if drives == 0:
        return total, []
    w = vic_weight + drives * drive_weight
    nv = total * vic_weight // w
    rem = total - nv
    per = rem // drives
    chunks = [per] * drives
    chunks[-1] += rem - per * drives
    return nv, chunks


def mode_tables(total: int, vic_weight: int, drive_weight: int) -> list[tuple[int, int, int, int]]:
    rows: list[tuple[int, int, int, int]] = []
    rows.append((total, 0, 0, 0))
    nv, ds = split_vic_drive(total, vic_weight, drive_weight, 1)
    rows.append((nv, ds[0], 0, 0))
    nv, ds = split_vic_drive(total, vic_weight, drive_weight, 2)
    rows.append((nv, ds[0], ds[1], 0))
    nv, ds = split_vic_drive(total, vic_weight, drive_weight, 3)
    rows.append((nv, ds[0], ds[1], ds[2]))
    per = total // 3
    rows.append((0, per, per, total - 2 * per))
    return rows


def c_array_words(name: str, values: list[int]) -> str:
    return f"static const unsigned int {name}[5] = {{" + ",".join(str(v) + "u" for v in values) + "};"


def c_array_u8(name: str, values: list[int]) -> str:
    return f"static const unsigned char {name}[5] = {{" + ",".join(str(v) + "u" for v in values) + "};"


def asm_bytes(data: bytes, per_line: int = 16) -> str:
    lines: list[str] = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        lines.append("        .byte " + ",".join(f"${b:02X}" for b in chunk))
    return "\n".join(lines)


def write_segments_asm(segments: list[tuple[str, int, bytes, str]]) -> None:
    lines: list[str] = [
        "; src/generated_vic20uc_segments.s -- generated by tools/make_vic20uc_inc.py",
        "; Q table for VIC-20 C host variants.",
        "; Upload-only 1541 payload is in build/vic20ucdrv.prg at $1E20.",
        "",
    ]

    for name, addr, data, segment in segments:
        if segment != "RODATA":
            continue
        lines.append(f".export _{name}")
        lines.append("")
        lines.append('.segment "RODATA"')
        lines.append("")
        lines.append(f"_{name}:")
        lines.append(f"        ; ${addr:04X}, {len(data)} bytes")
        lines.append(asm_bytes(data))
        lines.append("")

    out = SRC / "generated_vic20uc_segments.s"
    out.write_text("\n".join(lines), encoding="ascii", newline="\n")
    print(f"wrote {out}")

def build_overlay_prg(segments: list[tuple[str, int, bytes, str]]) -> tuple[int, bytes, dict[str, int]]:
    payload_parts: list[tuple[str, bytes]] = [
        (name, data) for name, _addr, data, segment in segments if segment != "RODATA"
    ]
    payload_len = sum(len(data) for _name, data in payload_parts)
    if OVERLAY_LOAD + payload_len > OVERLAY_END:
        raise ValueError(
            f"packed 1541 overlay ${OVERLAY_LOAD:04X}-${OVERLAY_LOAD + payload_len - 1:04X} "
            f"exceeds overlay end ${OVERLAY_END:04X}"
        )

    pos = OVERLAY_LOAD
    host_ptrs: dict[str, int] = {}
    body = bytearray()
    for name, data in payload_parts:
        host_ptrs[name] = pos
        body.extend(data)
        pos += len(data)

    prg = bytes((OVERLAY_LOAD & 0xFF, OVERLAY_LOAD >> 8)) + bytes(body)
    out = BUILD / f"{OVERLAY_NAME}.prg"
    out.write_bytes(prg)
    print(f"wrote {out}: packed screen overlay ${OVERLAY_LOAD:04X}-${pos - 1:04X} ({len(body)} bytes)")
    return OVERLAY_LOAD, bytes(body), host_ptrs

def main() -> None:
    total = checked_word(config.TOTAL_WORK, "TOTAL_WORK")
    jps = checked_word(getattr(config, "JIFFIES_PER_SECOND", 50), "JIFFIES_PER_SECOND")
    if total == 0:
        raise ValueError("TOTAL_WORK must be positive")
    if jps == 0:
        raise ValueError("JIFFIES_PER_SECOND must be positive")

    d = config.DRIVE
    drive_image = compact_drive_image()
    q_offset = d["table"] - d["load"]
    if q_offset < 0 or q_offset + 256 > len(drive_image):
        raise ValueError("compact drive image does not contain the Q table")
    expected_q = q_table()
    if drive_image[q_offset:q_offset + 256] != expected_q:
        raise ValueError("compact drive image Q table does not match generated Q table")

    segments = extract_segments(drive_image, int(d["load"]))
    write_segments_asm(segments)
    overlay_load, overlay_payload, host_ptrs = build_overlay_prg(segments)

    vic_weight = int(getattr(config, "VIC_WEIGHT", 100))
    drive_weight = int(config.DRIVE_WEIGHT)
    rows = mode_tables(total, vic_weight, drive_weight)
    workers = [sum(1 for v in row if v > 0) for row in rows]
    k_rows = [[v // 1000 if v else 0 for v in row] for row in rows]

    vic_seed = seed_pair("VIC_SEED", getattr(config, "VIC_SEED", (123, 45)))
    drive_seeds = getattr(config, "DRIVE_SEEDS", {})
    d8_seed = seed_pair("DRIVE_SEEDS[8]", drive_seeds.get(8, (37, 21)))
    d9_seed = seed_pair("DRIVE_SEEDS[9]", drive_seeds.get(9, (91, 173)))
    d10_seed = seed_pair("DRIVE_SEEDS[10]", drive_seeds.get(10, (211, 57)))

    seg_macros: list[str] = []
    seg_decls: list[str] = []
    for idx, (name, addr, data, segment) in enumerate(segments):
        seg_macros.append(f"#define DRIVE_SEG{idx}_ADDR     0x{addr:04X}u")
        seg_macros.append(f"#define DRIVE_SEG{idx}_LEN      {len(data)}u")
        if segment == "RODATA":
            seg_macros.append(f"#define DRIVE_SEG{idx}_PTR      {name}")
            seg_decls.append(f"extern const unsigned char {name}[DRIVE_SEG{idx}_LEN];")
        else:
            seg_macros.append(f"#define DRIVE_SEG{idx}_PTR      ((const unsigned char*)0x{host_ptrs[name]:04X}u)")

    text = f"""/* src/generated_vic20uc.h -- generated by tools/make_vic20uc_inc.py */
#ifndef GENERATED_VIC20UC_H
#define GENERATED_VIC20UC_H

#define TOTAL_WORK          {total}u
#define JIFFIES_PER_SECOND  {jps}u
#define DRIVE_LOAD          0x{d['load']:04X}u
#define DRIVE_PARAMS        0x{d['params']:04X}u
#define DRIVE_STATUS        0x{d['params'] + 3:04X}u
#define DRIVE_RESULT        0x{d['params'] + 4:04X}u
#define DRIVE_IMAGE_LEN     {len(drive_image)}u
#define DRIVE_OVERLAY_LOAD  0x{overlay_load:04X}u
#define DRIVE_OVERLAY_LEN   {len(overlay_payload)}u
#define DRIVE_SEG_COUNT     {len(segments)}u
#define Q_OFFSET            0x{q_offset:04X}u

#define VIC_SEED_LO         {vic_seed[0]}u
#define VIC_SEED_HI         {vic_seed[1]}u
#define D8_SEED_LO          {d8_seed[0]}u
#define D8_SEED_HI          {d8_seed[1]}u
#define D9_SEED_LO          {d9_seed[0]}u
#define D9_SEED_HI          {d9_seed[1]}u
#define D10_SEED_LO         {d10_seed[0]}u
#define D10_SEED_HI         {d10_seed[1]}u

{chr(10).join(seg_macros)}

{chr(10).join(seg_decls)}

{c_array_words('mode_nv', [row[0] for row in rows])}
{c_array_words('mode_n8', [row[1] for row in rows])}
{c_array_words('mode_n9', [row[2] for row in rows])}
{c_array_words('mode_na', [row[3] for row in rows])}
{c_array_u8('mode_workers', workers)}
{c_array_u8('mode_kv', [row[0] for row in k_rows])}
{c_array_u8('mode_k8', [row[1] for row in k_rows])}
{c_array_u8('mode_k9', [row[2] for row in k_rows])}
{c_array_u8('mode_ka', [row[3] for row in k_rows])}

#endif
"""
    out = SRC / "generated_vic20uc.h"
    out.write_text(text, encoding="ascii", newline="\n")
    print(f"wrote {out}")
    print(f"wrote {BUILD / 'vic20uc_drive.bin'}: {len(drive_image)} bytes")
    print(f"external 1541 overlay payload: {len(overlay_payload)} bytes")


if __name__ == "__main__":
    main()



# VIC20UC_MODE_LINE_POSTPROCESSOR
def _vic20uc_postprocess_header_mode_lines() -> None:
    # Generate MODE_LINE_x macros from mode_k* arrays and remove those arrays.
    # This preserves the compact UI for arbitrary TOTAL_WORK values while keeping
    # the final C build smaller: print_mode_line() prints generated strings and no
    # longer needs print_k() or mode_kv/mode_k8/mode_k9/mode_ka in RODATA.
    import re
    from pathlib import Path

    root = Path(__file__).resolve().parents[1]
    header_path = root / "src" / "generated_vic20uc.h"
    if not header_path.exists():
        return

    text = header_path.read_text(encoding="utf-8")

    def extract_u8_array(name: str) -> list[int]:
        m = re.search(
            rf"(?ms)^[ \t]*(?:static[ \t]+)?const[ \t]+(?:u8|unsigned[ \t]+char|char)"
            rf"[ \t]+{name}[ \t]*\[[^\]]*\][ \t]*=[ \t]*\{{(.*?)\}}[ \t]*;",
            text,
        )
        if not m:
            raise RuntimeError(f"generated_vic20uc.h: cannot find {name}[] for MODE_LINE generation")
        vals = re.findall(r"0x[0-9A-Fa-f]+|\d+", m.group(1))
        return [int(v, 0) for v in vals]

    kv = extract_u8_array("mode_kv")
    k8 = extract_u8_array("mode_k8")
    k9 = extract_u8_array("mode_k9")
    ka = extract_u8_array("mode_ka")
    if not (len(kv) == len(k8) == len(k9) == len(ka) == 5):
        raise RuntimeError("generated_vic20uc.h: expected five mode_k* values for MODE_LINE generation")

    def fmt_k(v: int) -> str:
        return "--" if v == 0 else str(v)

    lines = [
        f'#define MODE_LINE_{i} "m{i + 1} {fmt_k(kv[i])} {fmt_k(k8[i])} {fmt_k(k9[i])} {fmt_k(ka[i])}..."'
        for i in range(5)
    ]

    # Drop old/generated MODE_LINE defines, then remove the old mode_k* arrays.
    text = re.sub(r'(?m)^#define[ \t]+MODE_LINE_[0-4][ \t]+".*?"[ \t]*\n', "", text)

    for name in ("mode_kv", "mode_k8", "mode_k9", "mode_ka"):
        text = re.sub(
            rf"(?ms)^[ \t]*(?:static[ \t]+)?const[ \t]+(?:u8|unsigned[ \t]+char|char)"
            rf"[ \t]+{name}[ \t]*\[[^\]]*\][ \t]*=[ \t]*\{{.*?\}}[ \t]*;[ \t]*\n",
            "",
            text,
            count=1,
        )

    block = "\n/* Generated compact mode header lines. */\n" + "\n".join(lines) + "\n"

    # Insert before the final #endif if the header has a guard; otherwise append.
    matches = list(re.finditer(r"(?m)^#endif\b.*$", text))
    if matches:
        m = matches[-1]
        text = text[:m.start()] + block + "\n" + text[m.start():]
    else:
        text = text.rstrip() + "\n" + block

    header_path.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    _vic20uc_postprocess_header_mode_lines()
